
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertFromDhToEuro")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertFromDhToEuro", targetNamespace = "http://ws/", className = "proxy.ConvertFromDhToEuro")
    @ResponseWrapper(localName = "ConvertFromDhToEuroResponse", targetNamespace = "http://ws/", className = "proxy.ConvertFromDhToEuroResponse")
    @Action(input = "http://ws/BanqueService/ConvertFromDhToEuroRequest", output = "http://ws/BanqueService/ConvertFromDhToEuroResponse")
    public double convertFromDhToEuro(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "proxy.GetAccountResponse")
    @Action(input = "http://ws/BanqueService/getAccountRequest", output = "http://ws/BanqueService/getAccountResponse")
    public Compte getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://ws/", className = "proxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://ws/", className = "proxy.GetAccountsResponse")
    @Action(input = "http://ws/BanqueService/getAccountsRequest", output = "http://ws/BanqueService/getAccountsResponse")
    public List<Compte> getAccounts();

}
